name: echo YAML field presence
on:
  pull_request:
    types: [opened, synchronize]
      
jobs:
  build:
    name: echo YAML field presence
    runs-on: ubuntu-latest
    steps:
    - working-directory: testing_actions
      run: bash title_simpler.sh
